#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# Plot Problem 1_A Family 3 only sweep results
#
# This script plots results generated by:
#
#   experiment_mode = family3_candidate_pool_ablation
#
# Expected input structure:
#
#   outputs/protocol1a_family3_only/pred_<predictor>/
#     costs_*__sims_*__noise_<noise_tag>__scale_<scale_tag>/
#       protocol1a_modefamily3_candidate_pool_ablation_policyfantasy_poolall_protocols_pred<predictor>_trial0_seed0.json
#       protocol1a_modefamily3_candidate_pool_ablation_policyfantasy_pooltarget_only_pred<predictor>_trial0_seed0.json
#
# It filters by noise and observer scale, copies only valid result JSONs
# into a temporary root, and then calls:
#
#   python -m ofml_alfn.analysis.plot_protocol1a_sweep
#
# ============================================================

# ----------------------------
# User editable settings
# ----------------------------
PREDICTOR_TYPES=(
  "dkl"
  # "mcd"
)

BASE_ROOT="outputs/protocol1a_family3_only"
BASE_OUTPUT="outputs/protocol1a_sweep_plots_family3_only"
BASE_TMP="outputs/protocol1a_plot_temp_family3_only"

METRIC="target_test_loss"

# These should match the experiment bash that actually generated results.
# Current attached run script uses only:
#   noise = 1.0 0.5 0.0
#   scale = 0.5 1.0 2.0
NOISE_SETS=(
  "1.0 0.5 0.0"
  # "2.0 1.0 0.0"
  # "0.5 0.25 0.0"
)

SCALE_SETS=(
  # "1.0 1.0 1.0"
  "0.5 1.0 2.0"
  # "2.0 1.5 1.0"
)

# ----------------------------
# Utility
# ----------------------------
make_tag() {
  local triplet="$1"
  echo "$triplet" | tr ' ' '_' | tr '.' 'p'
}

log() {
  echo
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

has_family3_summary_json() {
  local combo_dir="$1"
  local predictor="$2"

  find "$combo_dir" \
    -maxdepth 1 \
    -type f \
    -name "protocol1a_modefamily3_candidate_pool_ablation_policyfantasy_pool*_pred${predictor}_trial*.json" \
    ! -name "*_selections.json" \
    | grep -q .
}

copy_family3_jsons() {
  local combo_dir="$1"
  local dst_dir="$2"
  local predictor="$3"

  mkdir -p "$dst_dir"

  find "$combo_dir" \
    -maxdepth 1 \
    -type f \
    \( \
      -name "protocol1a_modefamily3_candidate_pool_ablation_policyfantasy_pool*_pred${predictor}_trial*.json" \
      -o \
      -name "protocol1a_modefamily3_candidate_pool_ablation_policyfantasy_pool*_pred${predictor}_trial*_selections.json" \
    \) \
    -exec cp {} "$dst_dir"/ \;
}

# ----------------------------
# Main
# ----------------------------
for predictor in "${PREDICTOR_TYPES[@]}"; do
  ROOT_BASE="${BASE_ROOT}/pred_${predictor}"
  OUTPUT_BASE="${BASE_OUTPUT}/pred_${predictor}"
  TMP_BASE="${BASE_TMP}/pred_${predictor}"

  mkdir -p "$OUTPUT_BASE"
  mkdir -p "$TMP_BASE"

  if [[ ! -d "$ROOT_BASE" ]]; then
    log "Root directory does not exist. Skipping."
    echo "predictor = ${predictor}"
    echo "ROOT_BASE = ${ROOT_BASE}"
    continue
  fi

  for noise_triplet in "${NOISE_SETS[@]}"; do
    noise_tag="$(make_tag "$noise_triplet")"

    for scale_triplet in "${SCALE_SETS[@]}"; do
      scale_tag="$(make_tag "$scale_triplet")"

      filtered_root="${TMP_BASE}/noise_${noise_tag}__scale_${scale_tag}"
      filtered_output="${OUTPUT_BASE}/noise_${noise_tag}__scale_${scale_tag}"

      rm -rf "$filtered_root"
      mkdir -p "$filtered_root"
      mkdir -p "$filtered_output"

      found_any=0
      valid_any=0

      log "Searching result directories"
      echo "predictor = ${predictor}"
      echo "noise     = ${noise_triplet}"
      echo "scale     = ${scale_triplet}"
      echo "pattern   = ${ROOT_BASE}/costs_*__sims_*__noise_${noise_tag}__scale_${scale_tag}"

      shopt -s nullglob
      for combo_dir in "${ROOT_BASE}"/costs_*__sims_*__noise_"${noise_tag}"__scale_"${scale_tag}"; do
        found_any=1

        combo_name="$(basename "$combo_dir")"

        if has_family3_summary_json "$combo_dir" "$predictor"; then
          valid_any=1
          dst_combo_dir="${filtered_root}/${combo_name}"

          log "Adding valid combo directory"
          echo "source = ${combo_dir}"
          echo "dest   = ${dst_combo_dir}"

          copy_family3_jsons "$combo_dir" "$dst_combo_dir" "$predictor"
        else
          log "Skipping combo directory because no valid Family 3 summary JSON was found"
          echo "combo_dir = ${combo_dir}"
        fi
      done
      shopt -u nullglob

      if [[ "$found_any" -eq 0 ]]; then
        log "No matching result directories found"
        echo "predictor = ${predictor}"
        echo "noise     = ${noise_triplet}"
        echo "scale     = ${scale_triplet}"
        echo "pattern   = ${ROOT_BASE}/costs_*__sims_*__noise_${noise_tag}__scale_${scale_tag}"
        continue
      fi

      if [[ "$valid_any" -eq 0 ]]; then
        log "Matching directories were found, but none contained valid Family 3 summary JSON files"
        echo "predictor     = ${predictor}"
        echo "noise         = ${noise_triplet}"
        echo "scale         = ${scale_triplet}"
        echo "filtered_root = ${filtered_root}"
        find "$filtered_root" -maxdepth 3 -print
        continue
      fi

      log "Filtered input directory"
      echo "filtered_root = ${filtered_root}"
      find "$filtered_root" -maxdepth 2 -type f -name "*.json" | sort

      log "Plotting Family 3 ${predictor} results"
      echo "noise           = ${noise_triplet}"
      echo "scale           = ${scale_triplet}"
      echo "filtered_root   = ${filtered_root}"
      echo "filtered_output = ${filtered_output}"

      python -m ofml_alfn.analysis.plot_protocol1a_sweep \
        --root_dir "${filtered_root}" \
        --output_dir "${filtered_output}" \
        --metric "${METRIC}" \
        --title_prefix "Protocol 1A ${predictor} Family 3 noise=[${noise_triplet}] scale=[${scale_triplet}]"

      log "Finished plotting"
      echo "Output directory: ${filtered_output}"
    done
  done
done

log "All Family 3 plots finished."